# frozen_string_literal: true

require 'fileutils'

require 'simplecov'
require 'simplecov-console'
require 'simplecov_lcov_formatter'

SimpleCov::Formatter::LcovFormatter.config do |c|
  c.report_with_single_file = true
  c.lcov_file_name = 'actionmap.info'
  # c.single_report_path = 'your/path/lcov.info'
end

SimpleCov.start 'rails' do
  # This is so we can sum the coverage across the two cucumber CI steps.
  profile = ENV['CUCUMBER_PROFILE'] || ENV['PROFILE'] ||
            begin
              if (arg = ARGV.find { |a| a.start_with?('--profile=') })
                arg.split('=', 2)[1]
              elsif (idx = ARGV.index('-p') || ARGV.index('--profile'))
                ARGV[idx + 1]
              end
            end

  command_name "cucumber:#{profile}" if profile
  # enable_coverage :branch

  ## CS169: You may want to modify some of the testing configuration.

  # This only shows the more verbose console output on GitHub
  # You may choose to enable it locally.
  formatters = [
    SimpleCov::Formatter::LcovFormatter,
    SimpleCov::Formatter::HTMLFormatter
  ]
  formatters << SimpleCov::Formatter::Console if ENV.fetch('CI', nil)

  SimpleCov.formatters = SimpleCov::Formatter::MultiFormatter.new(formatters)
end

# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of Cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'cucumber/rails'
require 'axe-cucumber-steps'

# Capybara defaults to CSS3 selectors rather than XPath.
# If you'd prefer to use XPath, just uncomment this line and adjust any
# selectors in your step definitions to use the XPath syntax.
# Capybara.default_selector = :xpath

# By default, any exception happening in your Rails application will bubble up
# to Cucumber so that your scenario will fail. This is a different from how
# your application behaves in the production environment, where an error page will
# be rendered instead.
#
# Sometimes we want to override this default behaviour and allow Rails to rescue
# exceptions and display an error page (just like when the app is running in production).
# Typical scenarios where you want to do this is when you test your error pages.
# There are two ways to allow Rails to rescue exceptions:
#
# 1) Tag your scenario (or feature) with @allow-rescue
#
# 2) Set the value below to true. Beware that doing this globally is not
# recommended as it will mask a lot of errors for you!
#
ActionController::Base.allow_rescue = false

# Remove/comment out the lines below if your app doesn't have a database.
# For some databases (like MongoDB and CouchDB) you may need to use :truncation instead.
begin
  DatabaseCleaner.strategy = :truncation
rescue NameError
  raise 'You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it.'
end

# Enable Omniauth test mode so you don't need credentials in the test environment.
# You may want to edit `ApplicationHelper#login_enabled?` however.
OmniAuth.config.test_mode = true

# Ensure tests are always compiled.
# This runs once when Cucumber loads
system('bin/rails javascript:build css:build')

Before do
  Rails.application.load_seed
end

# You may also want to configure DatabaseCleaner to use different strategies for certain features and scenarios.
# See the DatabaseCleaner documentation for details. Example:
#
#   Before('@no-txn,@selenium,@culerity,@celerity,@javascript') do
#     # { except: [:widgets] } may not do what you expect here
#     # as Cucumber::Rails::Database.javascript_strategy overrides
#     # this setting.
#     DatabaseCleaner.strategy = :truncation
#   end
#
#   Before('not @no-txn', 'not @selenium', 'not @culerity', 'not @celerity', 'not @javascript') do
#     DatabaseCleaner.strategy = :transaction
#   end
#

# rubocop:disable Lint/Debugger
After('@a11y') do |scenario|
  name = scenario.respond_to?(:name) && scenario.name ? scenario.name : 'scenario'
  name = name.gsub(/^The\s*/i, '').gsub(/\s*Page/i, '')
  safe_name = name.gsub(/[^0-9A-Za-z.-]/, '_')[0..100]
  timestamp = Time.current.strftime('%Y%m%d-%H%M%S')
  base_dir = File.join(Dir.pwd, 'tmp', 'cucumber', "#{safe_name}-#{timestamp}")
  FileUtils.mkdir_p(base_dir)

  screenshot_path = File.join(base_dir, 'screenshot.png')
  html_path       = File.join(base_dir, 'page.html')

  # Try the common Capybara helpers; fall back to driver-specific render where available.
  # Chrome does not support passing `full: true`
  # If you want bigger screenshots, edit browsers.rb
  begin
    page.save_screenshot(screenshot_path)
  rescue StandardError
    begin
      Capybara.page.driver.render(screenshot_path) if Capybara.page.driver.respond_to?(:render)
    rescue StandardError
      # ignore if screenshot can't be produced
    end
  end

  begin
    page.save_page(html_path)
  rescue StandardError
    # ignore if HTML can't be saved
  end
end
# rubocop:enable Lint/Debugger

# Possible values are :truncation and :transaction
# The :transaction strategy is faster, but might give you threading problems.
# See https://github.com/cucumber/cucumber-rails/blob/master/features/choose_javascript_database_strategy.feature
Cucumber::Rails::Database.javascript_strategy = :truncation

World(FactoryBot::Syntax::Methods)
